### PR TITLE
Add Contributors Document

### PR DESCRIPTION
**Pull request by dmlb2000**
This adds a contributors document with an initial list. The empty
authors file is also removed.

Signed-off-by: David Brown <dmlb2000@gmail.com>

### CODE REVIEW

**Comment by dmlb2000** [comment]
@kauberry Could you verify that I didn't miss anyone, the thought here is that I'll reference this to resolve https://github.com/pacifica/pacifica-main-site/issues/68

**Comment by dmlb2000** [comment]
Need to check docs repo, Benjamin, Degan, Linda

**Review by kauberry — CHANGES_REQUESTED** [review]
Minor grammatical change to the footnote.

"If you want to be added feel free to put in an issue referencing your contribution" 

should be something like...

"If you have made contributions that are not recognized here, please submit an issue to the maintainers so that proper credit can be noted."

**Comment by kauberry** [comment]
Otherwise, the list looks just fine

**Pull request merged**
